version: '3'

services:
  web:
    build: .
    command: bash -c "cd nissen-hooper && yarn install && yarn dev"
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - '3000:3000'
